Use ordinary pint conversion only if both units are parsable by pint
IAMconsortium/pyam pull request #451
Opened 2020-10-30 22:16 UTC by coroa

# Please confirm that this PR has done the following:

- [x] Tests Added
- [ ] ~Documentation Added~
- [ ] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

Fixes #442 .

2020-10-31 08:25 UTC, danielhuppmann commented
thanks @coroa for tackling this issue! @khaeru, given that you have added this feature, it would be great if you could review...

2020-11-05 13:38 UTC, khaeru requested changes
The PR template asks for an addition to the release notes. It would also be best to change in the documentation to ensure the new/changed behaviour is fully & precisely described.

These, plus perhaps some text in the description at the top of this PR, are necessary to in order review the code/test changes.

2020-11-05 17:01 UTC, coroa commented
> It would also be best to change in the documentation to ensure the new/changed behaviour is fully & precisely described.

The behaviour is not supposed to change.

I can add small note to https://pyam-iamc.readthedocs.io/en/stable/tutorials/unit_conversion.html#4.-Use-contexts-to-specify-conversion-metrics , that `AR4GWP` (w/o the leading `gwp_` is also a permissible argument), but i would rather like to have your ok that this change stays before that.

Did the rest.

2020-11-05 17:22 UTC, khaeru commented
Currently the docs for `IamDataFrame.convert_unit()` say:
https://github.com/IAMconsortium/pyam/blob/c1ec71fdb43ac425c30c9ee37c8128fd514b1d9b/pyam/core.py#L937-L942

When integrating the iam_units package with pyam, I preserved the "gwp_" prefix because that's what was there previously, and I was trying to minimize changes. Personally, I very much agree it is simpler if this is not required: one less thing to explain and for the user to remember. So I welcome the change. @danielhuppmann as maintainer would have the final veto.

If it stays, then this docstring should be changed to something like:
```
…
In this case, *context* must be the name of a specific global warming potential
(GWP) metric supported by :mod:`iam_units`, e.g. 'AR5GWP100' (optionally
prefixed by 'gwp\_', e.g. 'gwp\_AR5GWP100').
```

This is what I mean by "precisely described".

2020-11-06 02:35 UTC, coroa commented on pyam/units.py
> +        return ret
```suggestion
    return None if inplace else ret
```

2020-11-06 11:20 UTC, danielhuppmann commented
Thanks @coroa and @khaeru! I agree that using the context name (`AR5-GWP100`) without leading `gwp_` as standard/recommended approach is preferred. I think the `gwp_*` approach is a legacy from an earlier implementation of the iam-units package. Fine for me to keep or mark as deprecated, to be removed in release >=10.0

2020-11-06 14:28 UTC, coroa commented
Great, then I'll update the PR to reflect this, ie include doc amendments and emit a deprecation warning for the longer context name.

2020-11-10 13:02 UTC, coroa commented
I think, I fixed all documentation correctly. The test failures look like an IIASA server issue.

2020-11-10 13:28 UTC, danielhuppmann commented on tests/test_units.py
> +    ('AR4GWP100', 'C', 11 / 3)
conversion from C to CO2 or CO2-eq shouldn't require a context at all, see https://github.com/IAMconsortium/units/issues/23 - adding a todo as a reminder to update the test

```suggestion
    # TODO remove context once IAMconsortium/units#23 is resolved
    ('AR4GWP100', 'C', 11 / 3)
```

2020-11-10 19:01 UTC, danielhuppmann approved these changes
Thank you @coroa!

2020-11-10 19:04 UTC, merged