Sankey plot
IAMconsortium/pyam pull request #466
Opened 2020-12-15 10:26 UTC by mabudz

# Please confirm that this PR has done the following:

- [ ] Tests Added
- [x] Documentation Added
- [x] Name of contributors Added to AUTHORS.rst
- [ ] Description in RELEASE_NOTES.md Added

# Description of PR

This PR introduces a function sankey() to create a basic Sankey diagram using plotly [https://plotly.com/python/sankey-diagram/].  This figure can be further modified (e.g. `fig.update_traces()`) or used (e.g. `fig.write_html()`) by the user [https://plotly.com/python/graph-objects/]

The function uses a  mapping dictionary {'variable1': ('source1', 'target1'), ...} to specify the source and the target node for the considered variables.

Currently only one region and one year can be plotted.

2020-12-15 10:39 UTC, danielhuppmann commented
there was an update of the sphinxcontrib-bibtex package and a change of the WorldBank data used in the pandas_datarader test, which currently causes unit tests to fail - don't worry about that for now

2020-12-15 10:45 UTC, mabudz commented
Alright. I just address the recommendations of picky Mr.Sticklers

2020-12-16 09:01 UTC, danielhuppmann requested changes
thanks @mabudz for this nice addition! a few suggestions to clean up the implementation... Also, I resolved all issues by stickler that you have implemented, but there are still a few stickler requests...

2020-12-16 12:29 UTC, danielhuppmann commented
I also just realized that you need to add `plotly` to the dependencies explicitly, i.e. [here](https://github.com/IAMconsortium/pyam/blob/a7a5f4f346ac4327678993db64aa3b91b596daf7/setup.py#L14)

2020-12-16 15:01 UTC, mabudz commented
Ah, I forgot to add the plotly dependencies. Should not do this while sitting on the airport :)))

2020-12-16 16:39 UTC, danielhuppmann approved these changes
One minor suggestion for a formatting clean-up inline, and please add to the release notes - then good to go! As discussed, we'll tackle an example for the plotting gallery and tests during/after the holidays...

2020-12-16 16:39 UTC, danielhuppmann commented on pyam/figures.py
> +                }
this section has to be indented (beyond the `.. code-block::`) to be displayed correctly
```suggestion
                {
                    variable: (source, target),
                }
```

2020-12-17 09:30 UTC, danielhuppmann commented
Merging and tackling the tests in a next iteration - thanks @mabudz!

2020-12-17 09:31 UTC, merged