prototype implementation for fast categorize with linting
IAMconsortium/pyam pull request #819
Opened 2024-02-27 17:06 UTC by gidden

This is only a prototype for now, but I hope shows how we could implement a fast categorization in line with previous work on `df.validate()`

# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [x] Name of contributors Added to AUTHORS.rst
- [ ] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

Please describe the changes introduced by this PR.

2024-03-12 11:11 UTC, gidden commented
Not clear to my why ruff CI is failing

2024-03-12 11:32 UTC, glatterf42 commented
The error message seems instructive to me:
```python
pyam/core.py:1:1: I001 [*] Import block is un-sorted or un-formatted
pyam/core.py:69:29: F401 [*] `pyam.validation._apply_criteria` imported but unused
Found 2 errors.
[*] 2 fixable with the `--fix` option.
```

We have recently introduced ruff in this repo, which can handle several nice things at once. For example, it sorts your import blocks and cleans up unused imports. All these fixes have been applied to the main branch, so if you rebase this PR on top of that, you'll automatically get them. If you don't want to do that for whatever reason, run `ruff check . --fix` in your local environment (or use `--diff` instead of `--fix` first to see what will happen) and commit the changes again :)

2024-03-12 11:35 UTC, glatterf42 commented
If you've done that and the action is still failing, please compare your local version with the one used for the check. Per default, GHA will use the [latest pypi release](https://pypi.org/project/ruff/), so 0.3.2.

2024-03-14 07:28 UTC, glatterf42 requested changes
Looks good to me in principle, but for this to be a proof of concept, I'd like to see a test case using the new behaviour and confirming that it works as intended.

Or am I misunderstanding this? The PR this one is following up on changed the call signature of `df.validate()`, but this one keeps `categorize()` the same, isn't it?

2024-03-14 07:33 UTC, glatterf42 approved these changes
Then the existing tests are enough for me :)

2024-03-14 09:41 UTC, gidden commented
Correct, all we do here is update the internals of `categorize()` to utilize another top-level API (`validate()`). I'd argue this is even more robust than depending on other internal-only functions. Maybe @danielhuppmann can quickly give a thumbs up?

2024-03-14 13:41 UTC, danielhuppmann commented
Will review tonight

2024-03-14 19:56 UTC, danielhuppmann commented
This PR does not actually implement the new signature of `validate()` using direct filters and upper/lower bound arguments, hence the deprecation warning (inherited from `validate()`) without being able to use the new signature would be probably very confusing to users. So I fully implemented this in a new branch building on the prototype by @gidden..

Closing in favor of #837

2024-03-14 19:56 UTC, closed without merging

2024-03-15 06:55 UTC, gidden commented
As an FYI, I was utilizing this prototype including the filters and upper/lower bound arguments. Code snippets that I was using are here:

in a `config.yaml`
```
  categorize:
    name: foo
    label: Medium Risk
    color: xkcd:baby blue
  criteria:
    upper_bound: 1000000
    lower_bound: 800000
    year: 2100
    region: World
 ```
 
 functioning code
```
        for key, data in self.definitions.items():
            if "categorize" not in data:
                continue
            logger.info(f"Preparing categorization for {key}")

            args = data["categorize"]
            self.db.categorize(
                args["name"],
                args["label"],
                variable=data["variable"],
                **data["criteria"],
                **{k: v for k, v in args.items() if k not in ["name", "label"]},
            )
```

2024-03-15 06:56 UTC, gidden commented on pyam/core.py
> +        not_valid = self.validate(criteria=criteria, **kwargs)
Here @danielhuppmann the validate kwargs like `upper_bound` and other filtering args are taken in

2024-03-15 07:01 UTC, danielhuppmann commented
Ok, right, the method works with the new signature, but it was not described in the docstring and there were no tests added in this PR - this is what I implemented in the new branch and PR.